cheats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/sign_up/', views.signup, name='signup'),
    path('menu/', views.menu, name='menu'),
    path('cheatsheets/', views.cheatsheets_index, name='cheatsheets_index'),
    path('cheatsheets/create/', views.CheatsheetCreate.as_view(),
         name='cheatsheets_create'),
    path('cheatsheets/<int:cheatsheet_id>/',
         views.cheatsheets_detail, name='cheatsheets_detail'),
    path('cheatsheets/<int:pk>/update/',
         views.CheatsheetUpdate.as_view(), name='cheatsheets_update'),
    path('cheatsheets/<int:pk>/delete/',
         views.CheatsheetDelete.as_view(), name='cheatsheets_delete'),
    path('cheatsheets/<int:cheatsheet_id>/add_review',
         views.add_review, name='add_review'),
    path('reviews/<int:pk>/update/',
         views.ReviewUpdate.as_view(), name='reviews_update'),
    path('reviews/<int:pk>/delete/',
         views.ReviewDelete.as_view(), name='reviews_delete'),
    path('cheatsheets/<int:cheatsheet_id>/add_favorite',
         views.add_favorite, name='add_favorite'),
    path('favorites/<int:pk>/delete/',
         views.FavoriteDelete.as_view(), name='favorites_delete'),
    path('favorites/', views.favorites_index, name='favorites_index'),
    path('cheatsheets/<int:cheatsheet_id>/add_photo/',
         views.add_photo, name='add_photo'),
    path('cheatsheets/create/add_photo/',
         views.add_photo, name='add_photo2'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.


class Cheatsheet(models.Model):
    title = models.CharField(max_length=100)
    topic = models.CharField(max_length=100)
    description = models.TextField(max_length=250, default="No description available yet")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cheatsheets_detail', kwargs={'cheatsheet_id': self.id})


class Review(models.Model):
    rating = models.IntegerField()
    comment = models.TextField(max_length=250)

    date = date.today()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cheatsheet = models.ForeignKey(Cheatsheet, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.rating}"

    def get_absolute_url(self):
        return reverse('cheatsheets_detail', kwargs={'cheatsheet_id': self.cheatsheet.id})


class Favorite(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cheatsheet = models.ForeignKey(Cheatsheet, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}"


class Photo(models.Model):
    url = models.CharField(max_length=200)
    cheatsheet = models.ForeignKey(Cheatsheet, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cheatsheet_id: {self.cheatsheet_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating','comment']

main_app/views.py
from site import check_enableusersite
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Cheatsheet, Review, Favorite, Photo
from .forms import ReviewForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
import uuid
import boto3
import os


# Create your views here.
def home(request):
    return render(request, 'home.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('menu')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/sign_up.html', context)


def menu(request):
    return render(request, 'menu.html')


def cheatsheets_index(request):
    cheatsheets = Cheatsheet.objects.all()
    photos = Photo.objects.all()
    return render(request, 'cheatsheets/index.html', {'cheatsheets': cheatsheets, 'photos': photos})


class CheatsheetCreate(LoginRequiredMixin, CreateView):
    model = Cheatsheet
    fields = ['title', 'topic','description']
    success_url = '/cheatsheets/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


def cheatsheets_detail(request, cheatsheet_id):
    cheatsheet = Cheatsheet.objects.get(id=cheatsheet_id)
    review_form = ReviewForm()
    favorites = Favorite.objects.all()
    return render(request, 'cheatsheets/detail.html', {
        'cheatsheet': cheatsheet,
        'review_form': review_form,
        'favorites': favorites,
    })


class CheatsheetUpdate(LoginRequiredMixin, UpdateView):
    model = Cheatsheet
    fields = ['topic','description']

    def get(self, request, pk):
        self.object = self.get_object()
        if self.object.user == self.request.user:
            return super().get(self, request, pk)
        else:
            return redirect('/cheatsheets/')

    def post(self, request, pk):
        self.object = self.get_object()
        if self.object.user == self.request.user:
            return super().post(self, request, pk)
        else:
            return redirect('/cheatsheets/')


class CheatsheetDelete(LoginRequiredMixin, DeleteView):
    model = Cheatsheet
    success_url = '/cheatsheets/'

    def get(self, request, pk):
        self.object = self.get_object()
        if self.object.user == self.request.user:
            return super().get(self, request, pk)
        else:
            return redirect('/cheatsheets/')

    def post(self, request, pk):
        self.object = self.get_object()
        if self.object.user == self.request.user:
            return super().post(self, request, pk)
        else:
            return redirect('/cheatsheets/')


@login_required
def add_review(request, cheatsheet_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.cheatsheet_id = cheatsheet_id
        new_review.user_id = request.user.id
        new_review.save()
    return redirect('cheatsheets_detail', cheatsheet_id=cheatsheet_id)


class ReviewUpdate(LoginRequiredMixin, UpdateView):
    model = Review
    fields = ['rating', 'comment']


class ReviewDelete(LoginRequiredMixin, DeleteView):
    model = Review
    success_url = '/cheatsheets/'


@login_required
def add_favorite(request, cheatsheet_id):
    f = Favorite()
    f.cheatsheet_id = cheatsheet_id
    f.user_id = request.user.id
    f.save()
    cheatsheet = Cheatsheet.objects.get(id=cheatsheet_id)
    review_form = ReviewForm()
    return render(request, 'cheatsheets/detail.html', {
        'cheatsheet': cheatsheet,
        'review_form': review_form,
    })


class FavoriteDelete(LoginRequiredMixin, DeleteView):
    model = Favorite
    success_url = '/favorites/'


@login_required
def favorites_index(request):
    favorites = Favorite.objects.all()
    cheatsheets = Cheatsheet.objects.all()
    photos = Photo.objects.all()
    return render(request, 'main_app/favorite_list.html', {'favorites': favorites, 'cheatsheets': cheatsheets,'photos':photos})


@login_required
def add_photo(request, cheatsheet_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, cheatsheet_id=cheatsheet_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('cheatsheets_detail', cheatsheet_id=cheatsheet_id)

main_app/templates/cheatsheets/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'css/cheatsheets/detail.css' %}">
  <title></title>
</head>
<body>
  <div class="container">
    <h1 class="title">{{ cheatsheet.title }}</h1>
    <div class="row">
        <div class="col s6">
          <div class="card">
            <div class="card-content">
              <p>Topic: {{ cheatsheet.topic }}</p>
            </div>
            {% for photo in cheatsheet.photo_set.all %}
            <img class="responsive-img card-panel" src="{{photo.url}}">
            {% empty %}
            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
            {% endfor %}
            {% if cheatsheet.user == request.user %}
            <form action="{% url 'add_photo' cheatsheet.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
              {% csrf_token %}
              <input type="file" name="photo-file">
              <br><br>
              <input type="submit" class="btn btn-success up_photo_btn" value="Upload Photo">
            </form>
            {% endif %}
            <div>
              <a class="btn btn-success add_fav_btn" href="{% url 'add_favorite' cheatsheet.id %}">Add Favorite</a>
            </div>
            
            <div class="card-footer">
              Created by {{ cheatsheet.user }}
              {% if cheatsheet.user == request.user %}
              <div class="card-action">
                <a href="{% url 'cheatsheets_update' cheatsheet.id %}" >Edit</a>
                <a href="{% url 'cheatsheets_delete' cheatsheet.id %}">Delete</a> 
              </div>
              {% endif %}

            </div>
          </div>
        </div>
    </div>
    
    <div class="col s6">
      <h1 class="review_title">Reviews</h1>
      <form action="{% url 'add_review' cheatsheet.id %}" method="POST">
        {% csrf_token %}
        {{ review_form.as_p }}
        <input type="submit" class="btn" value="Add Review">
      </form>
      <br>
      <!-- Show Reviews -->
      <table class="table table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Date</th>
            <th>Comment</th>
          </tr>
        </thead>
    
        <tbody>
          {% for review in cheatsheet.review_set.all %}
            <tr>
              <td>{{review.user}}</td>
              <td>{{review.date}}</td>
              <td>{{review.comment}}</td>
              <td>
                <a href="{% url 'reviews_update' review.id %}">Edit</a>
                <a href="{% url 'reviews_delete' review.id %}">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
  
</body>
</html>
{% endblock %}

main_app/templates/cheatsheets/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/cheatsheets/index.css' %}">
    <title>Cheatsheets Index</title>
</head>
<body>
    <h1>All Cheatsheets</h1>
    <div class="card-container">
        <div class="row">
            <div class="col">
                {% for cheatsheet in cheatsheets %}
                    <div class="card shadow">
                        <div class="card-header"><span class="card-title">{{ cheatsheet.title }}</span></div>
                        <div class="card-content">
                            <div id="photo_topic_container" class="row">
                                <div class="col">
                                    {% for photo in photos %}
                                        {% if photo.cheatsheet.id == cheatsheet.id %}
                                            <img class="card-image img-fluid" src="{{photo.url}}"> </img>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="col-sm-6">
                                    <p> {{ cheatsheet.topic }}</p>
                                    <p> {{ cheatsheet.description }} </p>
                                    <a class="btn btn-success" href="{% url 'cheatsheets_detail' cheatsheet.id %}">Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
    
    
</body>
</html>

{% endblock %}